[project]
name = "vllm-offline"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "torch>=2",
    "vllm>=0.5.4",
    "typer>=0.12.3",
]
readme = "README.md"
requires-python = ">= 3.11"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
